<?php

use Validatr\Validator;

class ValidatorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Validator
     */
    protected $validator;

    public function setUp()
    {
        //parent::setUp(); // TODO: Change the autogenerated stub
        $this->validator = new Validator();
    }


    public function falseRequiredValuesProvider()
    {
        return [
            'empty string' => [''],
            'null value' => [null],
            'empty string with 3 tabs' => ['   '],
        ];
    }

    /**
     * @dataProvider falseRequiredValuesProvider
     * @param $input
     */
    public function testValidateRequired($input)
    {
        $v = new Validator();
        $this->assertFalse($v->validateRequired($input));
    }

    public function testValidateMin()
    {
        $trueData = [
            ['fdfsfsf', 3],
            ['2dsh4353', 3],
            ['5', 3],
            [5, 3],
            ['1b245', 3],
            ['21b', 2],
            ['7.5', 2.3],
            ['2.4', '2.4']
        ];

        $falseData = [
            ['fdfsfsf', 7.5],
            ['2dsh4353', '32.41'],
            ['5', '5.01'],
            [4, 8],
            ['', 1],
            ['21b', '12'],
            ['2.3', 2.4]
        ];

        $v = new Validator();

        foreach($trueData as $row) {
            $this->assertTrue($v->validateMin($row[0], $row[1]));
        }

        foreach($falseData as $row) {
            $this->assertFalse($v->validateMin($row[0], $row[1]));
        }
    }

    public function testValidateMax()
    {
        $trueData = [
            ['fdfsfsf', 10],
            ['2dsh4353', 9.5],
            ['5', 7],
            [5, 6],
            ['', 1],
            ['1b245', 6],
            ['21b', 7],
            ['7.5', 7.55],
            ['2.4', '2.5'],
            [2.4, '2.5']
        ];

        $falseData = [
            [4, 2],
            ['fdfsfsf', 3.2],
            ['2dsh4353', '3.41'],
            ['5.01', '5.00'],
            ['vv', 1],
            ['21b', '2'],
            ['2.3', 2.1],
            [2.12, 1.89],
            [1.999, '1.99']
        ];

        $v = new Validator();

        foreach($trueData as $row) {
            $this->assertTrue($v->validateMax($row[0], $row[1]));
        }

        foreach($falseData as $row) {
            $this->assertFalse($v->validateMax($row[0], $row[1]));
        }
    }

    public function testValidateEmail()
    {
        $trueEmail = 'ok@petea.ru';
        $wrongEmail = 'ok@petearu';
        $this->assertTrue($this->validator->validateEmail($trueEmail));
        $this->assertFalse($this->validator->validateEmail($wrongEmail));
    }

    public function testValidateNumeric()
    {
        $trueData = [
            12, '12', 8.99, -7.03, '7.57', '024'
        ];

        $falseData = [
            'okay', 'superb', '22b', 'l12', '2,3', '02O'
        ];


        foreach($trueData as $number) {
            $this->assertTrue($this->validator->validateNumeric($number), "Error occured when input number was '{$number}'");
        }

        foreach($falseData as $number) {
            $this->assertFalse($this->validator->validateNumeric($number), "Error occured when input number was '{$number}'");
        }
    }

    public function testValidateBool()
    {
        $trueData = [
            1, true, 'true', 'on', 'yes'
        ];

        $falseData = [
            'okay', '12', false, 0, 0.2, 'ok', '22b', 'l12', '2,3', '2.3', '02O'
        ];

        foreach($trueData as $input) {
            $this->assertTrue($this->validator->validateBool($input), "Error occured when input number was '{$input}'");
        }

        foreach($falseData as $input) {
            $this->assertFalse($this->validator->validateBool($input), "Error occured when input number was '{$input}'");
        }
    }

    public function testValidateAlpha()
    {
        $trueData = [
            'okay', 'anotherString', 'true', 'false', 'null'
        ];

        $falseData = [
            null, false, '123', 123, 'okay2', '2okay', '01bada02', '^*%YGUT&^$^63', '!@#$%^&*()_+'
        ];

        foreach($trueData as $input) {
            $this->assertTrue($this->validator->validateAlpha($input), "Error occured when input number was '{$input}'");
        }

        foreach($falseData as $input) {
            $this->assertFalse($this->validator->validateAlpha($input), "Error occured when input number was '{$input}'");
        }
    }

    public function testValidateAlnum()
    {
        $trueData = [
            'okay', 'anotherString', 'true', 0, 12, 'false', 'null', 'stringWith123', '123WithString',
        ];

        $falseData = [
            false, null, '^*%YGUT&^$^63', '!@#$%^&*()_+', 'stringWith space', 'stringWith123With-+', '1 +12'
        ];

        foreach($trueData as $input) {
            $this->assertTrue($this->validator->validateAlnum($input), "Error occured when input number was '{$input}'");
        }

        foreach($falseData as $input) {
            $this->assertFalse($this->validator->validateAlnum($input), "Error occured when input number was '{$input}'");
        }
    }

    public function testValidateAlnumWith()
    {
        $trueData = [
            ['oka', '12'],
            ['ok234', 9],
            ['234ok', 'oka'],
            [125, 'k'],
            [125, 123],
            ['ok=unitTesting', '='],
            ['ok=da_unitTesting-ugu', '=_-'],
            ['some_string+numbers-$%^', '=_-!@#$%^&+'],
            ['%m,ok.word%&^', '&^.,/6367%^#'],
        ];

        $falseData = [
            ['ok-', 9],
            ['ok+_)', '_'],
            ['ok=unitTesting3.2', '='],
            ['ok=+-unitTesting', ''],
            ['ok=+-unitTesting12', '12'],
            ['12312+-', 'abc'],
            ['russian_symbols_окай', 'окай']
        ];

        foreach($trueData as $input) {
            $this->assertTrue($this->validator->validateAlnumWith($input[0], $input[1]), "Error occured when input number was '{$input[0]}'");
        }

        foreach($falseData as $input) {
            $this->assertFalse($this->validator->validateAlnumWith($input[0], $input[1]), "Error occured when input number was '{$input[0]}'");
        }
    }

    public function testValidateIn()
    {
        $this->assertTrue($this->validator->validateIn('two', 'one, two, three'));
        $this->assertFalse($this->validator->validateIn('four', 'one, two, three'));
    }

    public function testValidateNotIn()
    {
        $this->assertTrue($this->validator->validateNotIn('four', 'one, two, three'));
        $this->assertFalse($this->validator->validateNotIn('two', 'one, two, three'));
    }

    public function testValidateEqual()
    {
        $this->assertTrue($this->validator->validateEqual('one', 'one'));
        $this->assertFalse($this->validator->validateEqual('one', 'two'));
    }

    public function testValidateNotEqual()
    {
        $this->assertTrue($this->validator->validateNotEqual('one', 'two'));
        $this->assertFalse($this->validator->validateNotEqual('one', 'one'));
    }
}