<?php

use Validatr\Validator;

class ValidatorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Validator
     */
    protected $validator;

    public function setUp()
    {
        //parent::setUp(); // TODO: Change the autogenerated stub
        $this->validator = new Validator();
    }


    public function falseRequiredValuesProvider()
    {
        return [
            'empty string' => [''],
            'null value' => [null],
            'empty string with 3 tabs' => ['   '],
        ];
    }

    /**
     * @dataProvider falseRequiredValuesProvider
     * @param $input
     */
    public function testValidateRequired($input)
    {
        $v = new Validator();
        $this->assertFalse($v->validateRequired($input));
    }

    public function testValidateMin()
    {
        $trueData = [
            ['fdfsfsf', 3],
            ['2dsh4353', 3],
            ['5', 3],
            [5, 3],
            ['1b245', 3],
            ['21b', 2],
            ['7.5', 2.3],
            ['2.4', '2.4']
        ];

        $falseData = [
            ['fdfsfsf', 7.5],
            ['2dsh4353', '32.41'],
            ['5', '5.01'],
            [4, 8],
            ['', 1],
            ['21b', '12'],
            ['2.3', 2.4]
        ];

        $v = new Validator();

        foreach($trueData as $row) {
            $this->assertTrue($v->validateMin($row[0], $row[1]));
        }

        foreach($falseData as $row) {
            $this->assertFalse($v->validateMin($row[0], $row[1]));
        }
    }

    public function testValidateMax()
    {
        $trueData = [
            ['fdfsfsf', 10],
            ['2dsh4353', 9.5],
            ['5', 7],
            [5, 6],
            ['', 1],
            ['1b245', 6],
            ['21b', 7],
            ['7.5', 7.55],
            ['2.4', '2.5'],
            [2.4, '2.5']
        ];

        $falseData = [
            [4, 2],
            ['fdfsfsf', 3.2],
            ['2dsh4353', '3.41'],
            ['5.01', '5.00'],
            ['vv', 1],
            ['21b', '2'],
            ['2.3', 2.1],
            [2.12, 1.89],
            [1.999, '1.99']
        ];

        $v = new Validator();

        foreach($trueData as $row) {
            $this->assertTrue($v->validateMax($row[0], $row[1]));
        }

        foreach($falseData as $row) {
            $this->assertFalse($v->validateMax($row[0], $row[1]));
        }
    }

    public function testValidateEmail()
    {
        $trueEmail = 'ok@petea.ru';
        $wrongEmail = 'ok@petearu';
        $this->assertTrue($this->validator->validateEmail($trueEmail));
        $this->assertFalse($this->validator->validateEmail($wrongEmail));
    }

    public function testValidateNumeric()
    {
        $trueData = [
            12, '12', 8.99, '7.57', '024'
        ];

        $falseData = [
            'okay', 'superb', '22b', 'l12', '2,3', '02O'
        ];


        foreach($trueData as $number) {
            $this->assertTrue($this->validator->validateNumeric($number), "Error occured when input number was '{$number}'");
        }

        foreach($falseData as $number) {
            $this->assertFalse($this->validator->validateNumeric($number), "Error occured when input number was '{$number}'");
        }
    }

    public function testValidateBool()
    {
        $trueData = [
            1, true, 'true', 'on', 'yes'
        ];

        $falseData = [
            'okay', '12', false, 0, 0.2, 'ok', '22b', 'l12', '2,3', '2.3', '02O'
        ];

        foreach($trueData as $input) {
            $this->assertTrue($this->validator->validateBool($input), "Error occured when input number was '{$input}'");
        }

        foreach($falseData as $input) {
            $this->assertFalse($this->validator->validateBool($input), "Error occured when input number was '{$input}'");
        }
    }
}